#!/bin/sh

# Dirty solution to prevent ifup before brcmfmac is fully initialized

case "$1" in
  start)
        sleep 5
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

