#!/bin/sh

case "$1" in
  start)
        amixer cset name='Power Amplifier DAC Playback Switch' on
        amixer cset name='Power Amplifier Mute Switch' on
        amixer cset name='Power Amplifier Volume' 43 # This is -20dB
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

